name: Playwright Tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  test-tutorials:
    timeout-minutes: 40
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tutorial:
          - "run-prividium-guide"

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Install Dependencies
      run: bun install --frozen-lockfile
    - uses: actions/setup-node@v4
    - name: Start the docs
      run: bun pm2 start 'PORT=3030 bun dev' --name docs
    - name: Run test for ${{ matrix.tutorial }}
      uses: sarahschwartz/tutorial-tester@main
      with:
        tutorial-paths: '["zk-stack/prividium/run-prividium-chain"]'
        config-path: 'tests/prividium.ts'
        folder-name: 'prividium'
        wait-time: 300000
